<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-04-16T10:42:47 IST" name="Default suite" finished-at="2024-04-16T10:43:01 IST" duration-ms="13710">
    <groups>
    </groups>
    <test started-at="2024-04-16T10:42:47 IST" name="Default test" finished-at="2024-04-16T10:43:01 IST" duration-ms="13710">
      <class name="com.QA.Application.TestScripts.LoginScript">
        <test-method is-config="true" signature="generateReports()[pri:0, instance:com.QA.Application.TestScripts.LoginScript@611df6e3]" started-at="2024-04-16T10:42:47 IST" name="generateReports" finished-at="2024-04-16T10:42:47 IST" duration-ms="175" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- generateReports -->
        <test-method is-config="true" signature="setUp()[pri:0, instance:com.QA.Application.TestScripts.LoginScript@611df6e3]" started-at="2024-04-16T10:42:47 IST" name="setUp" finished-at="2024-04-16T10:42:51 IST" duration-ms="3623" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method signature="tc01VerifyLogin()[pri:1, instance:com.QA.Application.TestScripts.LoginScript@611df6e3]" started-at="2024-04-16T10:42:51 IST" name="tc01VerifyLogin" description="Verify URL" finished-at="2024-04-16T10:43:01 IST" duration-ms="9806" status="FAIL">
          <exception class="java.lang.IllegalArgumentException">
            <message>
              <![CDATA[testName cannot be null or empty]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.IllegalArgumentException: testName cannot be null or empty
at com.aventstack.extentreports.ExtentTest.<init>(ExtentTest.java:88)
at com.aventstack.extentreports.ExtentTest.<init>(ExtentTest.java:109)
at com.aventstack.extentreports.ExtentReports.createTest(ExtentReports.java:231)
at com.QA.Application.TestBase.TestBase.CreateExtentTest(TestBase.java:84)
at com.QA.Application.TestScripts.LoginScript.tc01VerifyLogin(LoginScript.java:12)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.IllegalArgumentException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tc01VerifyLogin -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.QA.Application.TestScripts.LoginScript@611df6e3]" started-at="2024-04-16T10:43:01 IST" name="tearDown" finished-at="2024-04-16T10:43:01 IST" duration-ms="239" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="closeReport()[pri:0, instance:com.QA.Application.TestScripts.LoginScript@611df6e3]" started-at="2024-04-16T10:43:01 IST" name="closeReport" finished-at="2024-04-16T10:43:02 IST" duration-ms="664" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeReport -->
      </class> <!-- com.QA.Application.TestScripts.LoginScript -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
